AllCops:
  TargetRubyVersion: 2.2

Style/AsciiComments:
  Enabled: false

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 15

Metrics/ClassLength:
  Max: 150

Metrics/AbcSize:
  Max: 20

Style/BracesAroundHashParameters:
  Enabled: false
